
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfjzjqebvvbpflcpdlux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmanpqcWVidnZicGZsY3BkbHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjExNDEsImV4cCI6MjA1NzU5NzE0MX0.IMcfn_ixr6FpoFnFQZb8E6ZpZweUXMaDGnJQ4IKDNXU";

// Define the Database type for analyses
export type AnalysesDB = {
  public: {
    Tables: {
      analyses: {
        Row: {
          id: string;
          user_id: string | null;
          startup_name: string;
          investibility_score: number;
          overall_risk: number;
          data: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          startup_name: string;
          investibility_score: number;
          overall_risk: number;
          data: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          startup_name?: string;
          investibility_score?: number;
          overall_risk?: number;
          data?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database & AnalysesDB>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
